### ISSUE TITLE
Higher Level Overview

### ISSUE THREAD

**Issue by arthur5005** [AfrikaBurn/TMI#1]
I understand this is trying to cover a lot of common ground and is designed to be generalized, but I'm struggling to understand the problems each of the components is trying to solve.

I feel a higher level narrative would help us understand the vision better and get more people involved. The entity diagrams lack context; as a first time reader, I want to quickly understand the importance of each of the components, why it matters and to whom.

Ideally we would have a paragraph or two, describing the overall problem & vision and we could add the following information to each components:

### Problem/Story:
As a **(role: Procurer/Ranger/Gate Person)**, I want to **(do a thing / solve a problem)**. 

*Describe the problem in detail*

Ideally I could just **(ideal vision)**

*Describe the ideal solution in very general terms*

### Solution:
_Offer a high level solution, describe how technology could solve it, it's moving pieces and it's relation to the individual solving the problem. *Then* we can include our entity and flow diagrams_.

An astute reader will notice that I used this format in describing my issue ;)

**Comment by scheepers** [comment]
Thanks, this is excellent feedback.

Will implement asap

**Comment by scheepers** [comment]
Hi Arthur,

We're a bit snowed under all round. Would you be interested in lending a
hand in whipping the documentation into shape?

scheepers

**Comment by scheepers** [comment]
Hi Arthur

We've overhauled the whole of the TMI github docs section and I'd love for
you to take another look:

https://github.com/AfrikaBurn/TMI

scheepers

**Comment by scheepers** [comment]
Write TMI user stories

**Comment by scheepers** [comment]
I'm creating separate issues for each of the systems.
