### ISSUE TITLE
Looking for contributors?

### ISSUE THREAD

**Issue by JHFarrant** [AfrikaBurn/TMI#2]
Hi, 
Are you looking for help in making TMI? If so what can I do?
A list of tasks and priorities would be quite useful. Potentially even using the projects feature?

> About me:
> I am a backend developer (mostly python) and I am going to my first Burn in 2020. I am based in london and sadly missed the hackathon last month. I do not have any ember experience but I am super keen to help out.

**Comment by Alabandit-AB** [comment]
Hey
We are definitely needing help! Currently, the next hackathon is set for the 28th, should have the details published today in time for tomorrows newsletter. Hackathon is a great way to catch up with exactly where we are and what the next steps are and how we need help.

If you direct message me your email, I will add you to the list of people that we are messaging about what we are doing. This week I am doing load balance testing ahead of the ticket sales, to make sure everything stays working as expected. 

I am hoping to have the second level of API open by the hackathon so people can start developing the new sections more effectively. 

Glad to have you on board!

**Comment by JHFarrant** [comment]
Ok great will do!
Cheers
