### ISSUE TITLE
Inventory Locations wireframe 

### ISSUE THREAD

**Issue by scheepers** [AfrikaBurn/TMI#32]
see https://github.com/AfrikaBurn/TMI/blob/master/docs/design.md#inventory
Locations are places that parts of inventory may go to and be checked into. In the case of  DPW examples of locations may include:
* AfrikaBurnHQ
* TankwaTown
* Anticlimax
* Decompression

In the case of a theme camp, Locations may include:
* TankwaTown
* Cape Town Storage
* Johannesburg Storage
* Afterglow

Actions possible on each Location list item:
* Check in
* Check out
* Edit
* Delete
* More

**Comment by TomMakkink** [comment]
Hi, 

I would like to help create this wireframe! I would just like to know some more details, such as which icon set you used for the original design? Also, what software did you use to create the existing wireframes? 

Regards, 
Tom

**Comment by scheepers** [comment]
Hello Tom!

Thanks for putting up your hand!

We used google draw and the material design icon set, with a couple of extra spices here and there.

You may find the original here:

https://docs.google.com/drawings/d/1g_Qd4y4Q8lDG6yiMOPAeWvK0oUdPTnjS33UdI7hzvdo/edit?usp=drivesdk

When you're done making changes, download it as SVG (Google Draw outputs some of the leanest SVG markup I've seen) and replace the SVG in a forked repo and make a pull request.

Here's a handy explainer if your not familiar with the process:

https://youtu.be/yr6IzOGoMsQ

I’m really excited to work with you!
Welcome!

Scheepers

**Comment by TomMakkink** [comment]
Fantastic thanks so much! I am also very excited! 

I should be able to get some pull requests in during the course of this week.

**Comment by scheepers** [comment]
This may also come in handy:

https://docs.google.com/presentation/d/1k8ppMFm6AsUwMZpBxXF2O5NYFfwPXBH_bfvDfSm-c3s

Scheepers
